/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TradeLogger {
  export type TradeRecordStruct = {
    tokenSymbol: string;
    chain: string;
    action: string;
    amountUsdCents: BigNumberish;
    confidenceScore: BigNumberish;
    status: string;
    timestamp: BigNumberish;
  };

  export type TradeRecordStructOutput = [
    tokenSymbol: string,
    chain: string,
    action: string,
    amountUsdCents: bigint,
    confidenceScore: bigint,
    status: string,
    timestamp: bigint
  ] & {
    tokenSymbol: string;
    chain: string;
    action: string;
    amountUsdCents: bigint;
    confidenceScore: bigint;
    status: string;
    timestamp: bigint;
  };
}

export interface TradeLoggerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRecentTrades"
      | "getTrade"
      | "logTrade"
      | "owner"
      | "tradeCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TradeLogged"): EventFragment;

  encodeFunctionData(
    functionFragment: "getRecentTrades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logTrade",
    values: [string, string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tradeCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getRecentTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logTrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tradeCount", data: BytesLike): Result;
}

export namespace TradeLoggedEvent {
  export type InputTuple = [
    id: BigNumberish,
    tokenSymbol: string,
    action: string,
    amountUsdCents: BigNumberish,
    confidenceScore: BigNumberish,
    status: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    tokenSymbol: string,
    action: string,
    amountUsdCents: bigint,
    confidenceScore: bigint,
    status: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    tokenSymbol: string;
    action: string;
    amountUsdCents: bigint;
    confidenceScore: bigint;
    status: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TradeLogger extends BaseContract {
  connect(runner?: ContractRunner | null): TradeLogger;
  waitForDeployment(): Promise<this>;

  interface: TradeLoggerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRecentTrades: TypedContractMethod<
    [n: BigNumberish],
    [TradeLogger.TradeRecordStructOutput[]],
    "view"
  >;

  getTrade: TypedContractMethod<
    [id: BigNumberish],
    [TradeLogger.TradeRecordStructOutput],
    "view"
  >;

  logTrade: TypedContractMethod<
    [
      tokenSymbol: string,
      chain: string,
      action: string,
      amountUsdCents: BigNumberish,
      confidenceScore: BigNumberish,
      status: string
    ],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  tradeCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRecentTrades"
  ): TypedContractMethod<
    [n: BigNumberish],
    [TradeLogger.TradeRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTrade"
  ): TypedContractMethod<
    [id: BigNumberish],
    [TradeLogger.TradeRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "logTrade"
  ): TypedContractMethod<
    [
      tokenSymbol: string,
      chain: string,
      action: string,
      amountUsdCents: BigNumberish,
      confidenceScore: BigNumberish,
      status: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tradeCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "TradeLogged"
  ): TypedContractEvent<
    TradeLoggedEvent.InputTuple,
    TradeLoggedEvent.OutputTuple,
    TradeLoggedEvent.OutputObject
  >;

  filters: {
    "TradeLogged(uint256,string,string,uint256,uint256,string,uint256)": TypedContractEvent<
      TradeLoggedEvent.InputTuple,
      TradeLoggedEvent.OutputTuple,
      TradeLoggedEvent.OutputObject
    >;
    TradeLogged: TypedContractEvent<
      TradeLoggedEvent.InputTuple,
      TradeLoggedEvent.OutputTuple,
      TradeLoggedEvent.OutputObject
    >;
  };
}
